-- ============================================================
-- SEED DATA: Bank Soal ISTC 2026
-- ============================================================
DELETE FROM public.questions;
INSERT INTO public.questions (nomor_soal, pertanyaan, pilihan_a, pilihan_b, pilihan_c, pilihan_d, kunci_jawaban, kategori) VALUES
(1, 'Tindakan berikut yang merupakan contoh penerapan prinsip Reduce (mengurangi sampah) adalah...', 'Mengolah botol plastik menjadi pot bunga', 'Membawa botol minum sendiri dari rumah', 'Menjual kertas bekas ke tempat daur ulang', 'Menggunakan kembali kardus bekas untuk wadah buku', 'B', 'environmental_technology'),
(2, 'Gas rumah kaca yang paling banyak dihasilkan dari sisa pembakaran bahan bakar fosil kendaraan adalah...', 'Oksigen', 'Karbon dioksida', 'Nitrogen', 'Uap air', 'B', 'environmental_technology'),
(3, 'Alat penangkap energi matahari yang mengonversi sinar matahari secara langsung menjadi listrik adalah...', 'Kincir angin', 'Panel surya (Solar cell)', 'Generator diesel', 'Turbin air', 'B', 'environmental_technology'),
(4, 'Pengolahan sampah daun dan sisa makanan menjadi pupuk organik dinamakan...', 'Komposting', 'Daur ulang', 'Insinerasi', 'Reboisasi', 'A', 'environmental_technology'),
(5, 'Keunggulan utama penggunaan bahan bakar biogas dari kotoran ternak dibandingkan bahan bakar fosil adalah...', 'Harganya sangat mahal', 'Bersifat terbarukan dan ramah lingkungan', 'Memiliki tekanan gas yang berbahaya', 'Menghasilkan asap hitam pekat', 'B', 'environmental_technology'),
(6, 'Proses penyaringan air laut menjadi air tawar yang dapat diminum dinamakan...', 'Aerasi', 'Desalinasi', 'Eutrofikasi', 'Sublimasi', 'B', 'environmental_technology'),
(7, 'Plastik biodegradable merupakan jenis plastik yang lebih ramah lingkungan karen', '..A. Tahan terhadap api suhu tinggi', 'Mudah terurai oleh mikroorganisme tanah', 'Tidak bisa berubah bentuk', 'Terbuat dari minyak bumi murni', 'B', 'environmental_technology'),
(8, 'Penanaman pohon kembali pada hutan yang gundul untuk menyerap CO2 disebut...', 'Tumpang sari', 'Reboisasi', 'Irigasi', 'Sanitasi', 'B', 'environmental_technology'),
(9, 'Contoh sumber energi terbarukan yang memanfaatkan panas dari dalam bumi adalah energi...', 'Geotermal', 'Biomasa', 'Nuklir', 'Gelombang', 'A', 'environmental_technology'),
(10, 'Sistem pertanian vertikal di area perkotaan yang hemat lahan dinamakan...', 'Permakultur', 'Vertical Farming / Vertikultur', 'Extensifikasi', 'Monokultur', 'B', 'environmental_technology'),
(11, 'Salah satu ciri bangunan ramah lingkungan (Green Building) adalah...', 'Menggunakan AC penuh sepanjang hari tanpa jendela', 'Memiliki banyak ventilasi dan pencahayaan alami', 'Seluruh dinding terbuat dari kaca tebal tertutup', 'Menggunakan lampu pijar berdaya besar', 'B', 'environmental_technology'),
(12, 'Istilah untuk sisa limbah barang-barang elektronik seperti HP dan komputer bekas adalah...', 'Organic waste', 'E-waste (Limbah elektronik)', 'Medical waste', 'Toxic gas', 'B', 'environmental_technology'),
(13, 'Menanam tanaman tanpa media tanah melainkan menggunakan air bernutrisi disebut...', 'Aquaponik', 'Hidroponik', 'Cangkok', 'Stek', 'B', 'environmental_technology'),
(14, 'Dampak negatif dari penggunaan kantong plastik sekali pakai terhadap laut adalah...', 'Air laut menjadi lebih asin', 'Hewan laut seperti penyu dapat mati karena memakan sampah plastik', 'Gelombang laut menjadi semakin besar', 'Terumbu karang tumbuh terlalu cepat', 'B', 'environmental_technology'),
(15, 'Teknologi irigasi yang menyalurkan air secara perlahan langsung ke akar tanaman agar hemat air adalah irigasi...', 'Sprinkler', 'Tetes (Drip irrigation)', 'Banjir', 'Saluran terbuka', 'B', 'environmental_technology'),
(16, 'Gabungan antara budidaya ikan dan tanaman hidroponik dalam satu sistem disebut...', 'Aeroponik', 'Akuaponik', 'Marikultur', 'Monokultur', 'B', 'environmental_technology'),
(17, 'Alat yang memanfaatkan hembusan angin untuk memutar generator listrik dinamakan...', 'Anemometer', 'Turbin angin', 'Barometer', 'Kompresor', 'B', 'environmental_technology'),
(18, 'Menggunakan kembali botol kaca bekas sirup untuk tempat air minum dingin di kulkas merupakan penerapan prinsip...', 'Reduce', 'Reuse', 'Recycle', 'Replace', 'B', 'environmental_technology'),
(19, 'Gas metana yang dihasilkan dari tempat pembuangan akhir (TPA) sampah berasal dari proses penguraian secar', '..A. Aerob (butuh udara)', 'Anaerob (tanpa udara)', 'Pembakaran', 'Pembekuan', 'B', 'environmental_technology'),
(20, 'Penggunaan lampu hemat energi yang paling efektif saat ini adalah jenis lampu...', 'Pijar', 'LED', 'Neon tabung biasa', 'Halogen', 'B', 'environmental_technology'),
(21, 'Fenomena masuknya polutan ke lingkungan perairan sehingga menurunkan kualitas air disebut...', 'Hujan asam', 'Pencemaran air', 'Asidifikasi', 'Efek rumah kaca', 'B', 'environmental_technology'),
(22, 'Kemampuan tanaman tertentu dalam menyerap dan membersihkan zat beracun dari tanah disebut...', 'Bioremediasi', 'Fitoremediasi', 'Oksidasi', 'Fermentasi', 'B', 'environmental_technology'),
(23, 'Keuntungan utama kendaraan listrik (Electric Vehicle) dibanding kendaraan bensin adalah...', 'Tidak menghasilkan emisi gas buang langsung', 'Tidak menggunakan baterai', 'Lebih berat dan lambat', 'Membutuhkan oli mesin lebih banyak', 'A', 'environmental_technology'),
(24, 'Cara menghemat listrik di rumah yang paling mudah adalah...', 'Membiarkan TV menyala saat tidur', 'Mematikan lampu dan alat elektronik yang tidak digunakan', 'Menyandarkan kulkas dekat kompor', 'Menggunakan AC pada suhu paling dingin 16°C dengan pintu terbuka', 'B', 'environmental_technology'),
(25, 'Penggunaan air bekas cucian beras untuk menyiram tanaman bertujuan untuk...', 'Membunuh tanaman', 'Menghemat air bersih dan memberikan nutrisi pada tanah', 'Memuat tanah menjadi keras', 'Mengusir serangga secara cepat', 'B', 'environmental_technology'),
(26, 'Bahan baku utama pembuatan bioetanol yang sering digunakan adalah tanaman yang mengandung...', 'Gula atau pati (seperti singkong dan tebu)', 'Minyak kelapa', 'Kayu keras', 'Batu bara', 'A', 'environmental_technology'),
(27, 'Salah satu penyebab utama terjadinya banjir di daerah perkotaan adalah...', 'Banyaknya taman kota', 'Berkurangnya daerah resapan air akibat penutupan beton', 'Penanaman pohon pembersih udara', 'Penggunaan sumur resapan', 'B', 'environmental_technology'),
(28, 'Fungsi dari pemanenan air hujan (Rainwater harvesting) adalah...', 'Memperbanyak nyamuk', 'Menampung air hujan untuk menyiram tanaman dan mencuci kendaraan', 'Menjadikan air hujan sebagai sumber listrik utama', 'Mengeringkan sumur warga', 'B', 'environmental_technology'),
(29, 'Kerusakan lapisan ozon di atmosfer bumi terutama disebabkan oleh zat kimi', '..A. Karbon monoksida', 'CFC (Chlorofluorocarbon) dari pendingin tua', 'Oksigen', 'Nitrogen dioksida', 'B', 'environmental_technology'),
(30, 'Pengolahan limbah plastik menjadi barang kerajinan tangan dinamakan...', 'Insinerasi', 'Upcycling / Daur ulang kreatif', 'Reboisasi', 'Distilasi', 'B', 'environmental_technology'),
(31, 'Istilah Carbon Footprint (Jejak Karbon) menggambarkan...', 'Bekas telapak kaki di tanah berkarbon', 'Jumlah total emisi gas rumah kaca yang dihasilkan dari aktivitas kita', 'Luas hutan yang ada di suatu negara', 'Berat batu bara yang ditambang', 'B', 'environmental_technology'),
(32, 'Alat penyaring udara yang dipasang di pabrik untuk mengurangi emisi debu halus adalah...', 'Filter air', 'Filter asap / Scrubber', 'Kompresor udara', 'Sensor angin', 'B', 'environmental_technology'),
(33, 'Microplastic berbahaya bagi ekosistem laut karen', '..A. Menambah nutrisi ikan', 'Termakan oleh hewan laut dan masuk ke dalam rantai makanan', 'Mempercepat pertumbuhan terumbu karang', 'Mengubah warna air menjadi bening', 'B', 'environmental_technology'),
(34, 'Energi gelombang laut memanfaatkan...', 'Panas permukaan air', 'Pergerakan naik turun permukaan air laut akibat angin', 'Kandungan garam air laut', 'Kedalaman air laut', 'B', 'environmental_technology'),
(35, 'Hutan bakau (mangrove) di pesisir pantai berfungsi untuk...', 'Mempercepat abrasi pantai', 'Mencegah erosi pantai dan tempat berkembang biak biota laut', 'Menyerap air laut agar surut', 'Menghasilkan kayu bakar utama', 'B', 'environmental_technology'),
(36, 'Mengubah sampah organik rumah tangga menjadi gas masak dinamakan alat...', 'Insinerator', 'Biodigester', 'Kompresor', 'Radiator', 'B', 'environmental_technology'),
(37, 'Bahan bakar biodiesel terbuat dari...', 'Minyak bumi', 'Minyak nabati (seperti kelapa sawit)', 'Gas alam cair', 'Batu bara cair', 'B', 'environmental_technology'),
(38, 'Usaha mengurangi penggunaan sterofom wadah makanan diganti dengan wadah kotak makan adalah tindakan...', 'Recycle', 'Replace / Replace', 'Refuse', 'Rot', 'B', 'environmental_technology'),
(39, 'Sumber energi air (PLTA) memanfaatkan...', 'Bau air', 'Energi potensial dan kinetik dari aliran air terjun/bendungan', 'Kejernihan air', 'Suhu dingin air', 'B', 'environmental_technology'),
(40, 'Konsep kota cerdas yang terintegrasi dengan teknologi ramah lingkungan dinamakan...', 'Industrial City', 'Smart & Green City', 'Megacity', 'Metropolis', 'B', 'environmental_technology'),
(41, 'Gas beracun tak berwarna dan tak berbau dari asap pembakaran tidak sempurna kendaraan adalah...', 'CO₂', 'CO  (Karbon Monoksida)', 'O₃', 'N₂', 'B', 'environmental_technology'),
(42, 'Penggunaan deterjen ramah lingkungan bertujuan agar...', 'Busa melimpah memenuhi sungai', 'Mudah terurai dan tidak merusak ekosistem sungai', 'Baju cepat lapuk', 'Air menjadi berwarna keruh', 'B', 'environmental_technology'),
(43, 'Kompos cair yang dibuat dari ekstrak sampah organik dinamakan...', 'Pupuk kimia Urea', 'Pupuk Organik Cair (POC)', 'Pestisida sintetis', 'NPK', 'B', 'environmental_technology'),
(44, 'Manfaat membuat lubang biopori di pekarangan rumah adalah...', 'Tempat pembuangan plastik', 'Meningkatkan resapan air hujan ke tanah dan mengolah sampah organik', 'Tempat memasang tiang listrik', 'Mengeringkan tanah di sekitarnya', 'B', 'environmental_technology'),
(45, 'Pembangkit Listrik Tenaga Bayu (PLTB) memanfaatkan sumber day', '..A. Air', 'Angin', 'Matahari', 'Panas bumi', 'B', 'environmental_technology'),
(46, 'Hujan asam terjadi apabila asap industri bereaksi dengan uap air membentuk zat...', 'Asam sulfat dan asam nitrat', 'Garam dapur', 'Alkohol', 'Amonia', 'A', 'environmental_technology'),
(47, 'Mengolah kertas bekas menjadi koran atau karton kembali adalah proses...', 'Reuse', 'Recycle', 'Reduce', 'Repair', 'B', 'environmental_technology'),
(48, 'Komposisi utama sampah rumah tangga di Indonesia sebagian besar berup', '..A. Plastik tebal', 'Sampah organik/sisa makanan', 'Kaca dan logam', 'Baterai bekas', 'B', 'environmental_technology'),
(49, 'Fungsi utama Atap Hijau (Green Roof) pada gedung modern adalah...', 'Menambah berat beban gedung', 'Menyerap panas, mengurangi efek rumah kaca, dan menampung air hujan', 'Tempat memarkir kendaraan', 'Menyimpan barang bekas', 'B', 'environmental_technology'),
(50, 'Gerakan menghemat energi dengan mematikan lampu selama 1 jam secara global dikenal dengan...', 'Earth Hour', 'Earth Day', 'Green Day', 'Clean Up Day', 'A', 'environmental_technology'),
(51, 'Bagian pada robot yang berfungsi menerima informasi dari lingkungan sekitar disebut...', 'Aktuator', 'Sensor', 'Mikrokontroler', 'Baterai', 'B', 'smart_robotics'),
(52, 'Sensor yang digunakan robot untuk mengukur jarak halangan menggunakan pantulan gelombang suara adalah...', 'Sensor LDR', 'Sensor Ultrasonik', 'Sensor Suhu', 'Sensor Sentuh', 'B', 'smart_robotics'),
(53, 'Komponen robot yang bertugas mengubah energi listrik menjadi gerakan roda adalah...', 'Sensor', 'Motor DC / Aktuator', 'Resistor', 'LED', 'B', 'smart_robotics'),
(54, 'Papan sirkuit kecil yang bertugas sebagai "otak" pengolah perintah pada robot dinamakan...', 'Transistor', 'Mikrokontroler (misal: Arduino)', 'Breadboard', 'Kapasitor', 'B', 'smart_robotics'),
(55, 'Sensor LDR (Light Dependent Resistor) berubah nilai hambatan listriknya berdasarkan...', 'Suhu udara', 'Intensitas cahaya', 'Suara keras', 'Getaran tanah', 'B', 'smart_robotics'),
(56, 'Jenis motor yang dapat berputar dengan sudut yang sangat presisi (misal 90 derajat) adalah...', 'Motor DC biasa', 'Motor Servo', 'Dinamo mainan', 'Generator AC', 'B', 'smart_robotics'),
(57, 'Robot Line Follower dapat mengikuti garis di lantai karena mendeteksi perbedaan warna menggunakan sensor...', 'Inframerah / Cahaya', 'Suara', 'Kelembaban', 'Gas', 'A', 'smart_robotics'),
(58, 'Komponen penyimpan energi listrik yang menjadi sumber daya utama robot adalah...', 'Resistor', 'Baterai', 'Sakelar', 'Dioda', 'B', 'smart_robotics'),
(59, 'Sensor PIR (Passive Infrared) pada robot pintar biasanya digunakan untuk mendeteksi...', 'Warna benda', 'Pergerakan manusia atau makhluk hidup', 'Tingkat kebisingan', 'Jarak dinding', 'B', 'smart_robotics'),
(60, 'Komponen buzzer pada robot berfungsi untuk...', 'Menampilkan gambar', 'Mengeluarkank bunyi atau nada peringatan', 'Menggerakkan kaki robot', 'Menyerap panas', 'B', 'smart_robotics'),
(61, 'Papan berlubang-lubang yang digunakan untuk merangkai komponen elektronik tanpa perlu menyolder dinamakan...', 'PCB', 'Breadboard / Protoboard', 'Motherboard', 'Harddisk', 'B', 'smart_robotics'),
(62, 'Lampu kecil yang biasa digunakan sebagai indikator status pada robot dinamakan...', 'LDR', 'LED', 'LCD', 'Relay', 'B', 'smart_robotics'),
(63, 'Sensor DHT11 pada proyek robotika digunakan untuk mengukur...', 'Jarak dan Kecepatan', 'Suhu dan Kelembaban udara', 'Cahaya dan Warna', 'Tekanan air', 'B', 'smart_robotics'),
(64, 'Komponen elektronik yang berfungsi membatasi arus listrik agar LED tidak terbakar adalah...', 'Kapasitor', 'Resistor', 'Transistor', 'Induktor', 'B', 'smart_robotics'),
(65, 'Robot yang bergerak menggunakan roda dinamakan robot jenis...', 'Legged Robot', 'Wheeled Robot', 'Drone', 'Humanoid', 'B', 'smart_robotics'),
(66, 'Driver motor (seperti L298N) dipasang di antara mikrokontroler dan motor dengan tujuan...', 'Mempercantik robot', 'Mengalirkan arus besar yang dibutuhkan motor tanpa merusak mikrokontroler', 'Menghitung jumlah langkah', 'Mengisi daya baterai', 'B', 'smart_robotics'),
(67, 'Layar kecil yang dipasang pada robot untuk menampilkan teks bacaan dinamakan...', 'LED', 'LCD Display', 'LDR', 'Solenoid', 'B', 'smart_robotics'),
(68, 'Sinyal PWM (Pulse Width Modulation) pada Arduino sering digunakan untuk mengatur...', 'Warna lampu', 'Kecepatan putaran motor DC', 'Kapasitas memori', 'Frekuensi suara', 'B', 'smart_robotics'),
(69, 'Sensor sentuh mekanis berupa sakelar kecil yang tertekan saat menabrak dinding dinamakan...', 'Limit switch / Bump sensor', 'Gyroscope', 'Barometer', 'Potensiometer', 'A', 'smart_robotics'),
(70, 'Robot yang dibentuk menyerupai anatomi tubuh manusia (memiliki kepala, 2 tangan, 2 kaki) dinamakan...', 'Manipulator', 'Humanoid', 'Quadruped', 'ROV', 'B', 'smart_robotics'),
(71, 'Kebalikan dari sensor yang menerima masukan, komponen yang menghasilkan keluaran (output) fisik disebut...', 'Transduser', 'Aktuator', 'Prosesor', 'Input device', 'B', 'smart_robotics'),
(72, 'Modul nirkabel Bluetooth (seperti HC-05) dipasang pada robot agar robot dapat...', 'Terbang', 'Dikendalikan secara jarak jauh melalui Smartphone', 'Berjalan tanpa baterai', 'Mengisi daya otomatis', 'B', 'smart_robotics'),
(73, 'Aplikasi/software tempat kita mengetikkan kode program untuk diunggah ke Arduino dinamakan...', 'Microsoft Word', 'Arduino IDE', 'Corel Draw', 'Photoshop', 'B', 'smart_robotics'),
(74, 'Komponen sakelar elektronik yang digerakkan secara elektromagnetik untuk mengontrol arus tegangan tinggi adalah...', 'Dioda', 'Relay', 'Kapasitor', 'Transistor', 'B', 'smart_robotics'),
(75, 'Sensor yang dapat mengukur kemiringan dan keseimbangan robot adalah...', 'Sensor Gas', 'Gyroscope / MPU6050', 'Sensor Hujan', 'Sensor Api', 'B', 'smart_robotics'),
(76, 'Istilah Autonomous Robot berarti robot tersebut...', 'Harus selalu dicolok ke kabel listrik', 'Mampu bekerja dan mengambil keputusan sendiri secara otomatis', 'Dikendalikan oleh remot kontrol manual penuh', 'Tidak memiliki sistem elektronik', 'B', 'smart_robotics'),
(77, 'Kabel-kabel kecil berujung jarum yang digunakan untuk menghubungkan komponen di breadboard disebut kabel...', 'USB', 'Jumper (Male/Female)', 'Listrik PLN', 'Coaxial', 'B', 'smart_robotics'),
(78, 'Pin VCC pada modul sensor elektronik umumnya dihubungkan ke kutub...', 'Negatif / Ground (GND)', 'Positif (Daya +5V atau +3.3V)', 'Signal digital', 'Antena', 'B', 'smart_robotics'),
(79, 'Pin GND pada papan rangkaian robot berarti...', 'General Node', 'Ground / Kutub Negatif (0V)', 'Green Diode', 'Power Input', 'B', 'smart_robotics'),
(80, 'Sensor yang mendeteksi keberadaan percikan api untuk robot pemadam kebakaran dinamakan...', 'Flame Sensor', 'Rain Sensor', 'Soil Sensor', 'Sound Sensor', 'A', 'smart_robotics'),
(81, 'Sensor kelembaban tanah (Soil Moisture Sensor) sangat berguna jika diterapkan pada proyek robotik...', 'Robot pembersih kaca', 'Robot penyiram tanaman otomatis', 'Robot pengantar makanan', 'Robot sepak bola', 'B', 'smart_robotics'),
(82, 'Bahasa pemrograman yang menjadi dasar pengodean pada Arduino berbasis pada bahas', '..A. Python', 'C / C++', 'HTML', 'Scratch', 'B', 'smart_robotics'),
(83, 'Dalam program Arduino, blok fungsi loop() berguna untuk...', 'Menjalankan perintah hanya satu kali saat dinyalakan', 'Menjalankan perintah secara berulang-ulang terus menerus', 'Menghentikan program', 'Menghapus kode program', 'B', 'smart_robotics'),
(84, 'Untuk menunda gerakan robot selama 1 detik pada program Arduino, perintah yang ditulis adalah...', 'wait(1);', 'delay(1000);', 'stop(100);', 'pause(10);', 'B', 'smart_robotics'),
(85, 'Roda serbaguna di bagian belakang robot roda dua yang dapat berputar bebas ke segala arah disebut rod', '..A. Castor', 'Offroad', 'Rantai', 'Ban dalam', 'A', 'smart_robotics'),
(86, 'Komponen pembagi tegangan variabel yang diputar dengan tangan untuk mengatur volume/kecepatan adalah...', 'Resistor tetap', 'Potensiometer', 'Dioda Zener', 'Transformator', 'B', 'smart_robotics'),
(87, 'Kamera cerdas yang digunakan robot untuk mengenali bentuk wajah manusia menggunakan teknologi...', 'Sound Detection', 'Computer Vision', 'Thermal Sensor', 'Proximity', 'B', 'smart_robotics'),
(88, 'Sensor yang bekerja memancarkan sinar infra merah dan menerima pantulannya untuk mendeteksi benda dekat disebut...', 'Sensor Proximity IR', 'Sensor Barometer', 'Sensor pH', 'Sensor Karbon', 'A', 'smart_robotics'),
(89, 'Jenis motor stepper sering digunakan pada mesin 3D Printer atau lengan robot presisi karen', '..A. Harganya sangat murah', 'Gerakannya dapat diatur per-langkah (step) secara sangat akurat', 'Tidak memerlukan listrik', 'Kecepatannya paling tinggi di dunia', 'B', 'smart_robotics'),
(90, 'Robot lengan yang banyak dipasang di pabrik perakitan mobil dinamakan...', 'Robot Bipedal', 'Arm Robot / Manipulator', 'Drone', 'Hovercraft', 'B', 'smart_robotics'),
(91, 'Penggunaan GPS pada robot pemotong rumput otonom berguna untuk...', 'Memotong rumput', 'Menentukan koordinat lokasi dan navigasi luar ruangan', 'Mengukur tinggi rumput', 'Mengisi baterai', 'B', 'smart_robotics'),
(92, 'Komponen penyearah arus listrik yang hanya mengalirkan arus ke satu arah saja adalah...', 'Resistor', 'Dioda', 'Kapasitor', 'Induktor', 'B', 'smart_robotics'),
(93, 'Komunikasi data nirkabel berbasis gelombang radio jarak pendek yang ada pada HP dan mikrokontroler adalah...', 'Wi-Fi dan Bluetooth', 'Kabel LAN', 'Serat Optik', 'Satelit', 'A', 'smart_robotics'),
(94, 'Untuk membaca sinyal dari tombol tekan (push button) pada Arduino, kita menggunakan perintah...', 'digitalWrite()', 'digitalRead()', 'analogWrite()', 'serialPrint()', 'B', 'smart_robotics'),
(95, 'Sensor air yang mendeteksi adanya tetesan air hujan adalah...', 'Rain Sensor', 'Gas Sensor MQ-2', 'Touch Sensor', 'Color Sensor', 'A', 'smart_robotics'),
(96, 'Struktur perintah logika yang digunakan untuk membuat keputusan pilihan pada robot (misal: "JIKA ada halangan MAKA belok") adalah...', 'for', 'if - else', 'while', 'void', 'B', 'smart_robotics'),
(97, 'Robot kapal kapal bawah laut tanpa awak dinamakan...', 'UAV', 'ROV / AUV (Submersible)', 'Drone', 'AGV', 'B', 'smart_robotics'),
(98, 'Komponen elektronik yang berfungsi menyimpan muatan listrik sementara adalah...', 'Resistor', 'Kapasitor', 'Transistor', 'Sakelar', 'B', 'smart_robotics'),
(99, 'Fungsi sensor warna (seperti TCS3200) pada robot pemilah barang adalah...', 'Mengukur berat barang', 'Mendeteksi warna RGB dari objek', 'Menghitung jumlah barang', 'Memindahkan barang', 'B', 'smart_robotics'),
(100, 'Singkatan dari teknologi IoT yang menyambungkan perangkat robotik ke jaringan internet adalah...', 'Input of Things', 'Internet of Things', 'Integration of Technology', 'Internal of Telecom', 'B', 'smart_robotics'),
(101, 'Dalam percobaan ilmiah, faktor yang sengaja diubah-ubah oleh peneliti dinamakan variabel...', 'Terikat', 'Bebas', 'Kontrol', 'Pengganggu', 'B', 'science_in_action'),
(102, 'Alat ukur panjang yang memiliki ketelitian hingga 0,1 mm dan dapat mengukur diameter dalam botol adalah...', 'Mistar', 'Jangka sorong', 'Mikrometer sekrup', 'Meteran gulung', 'B', 'science_in_action'),
(103, 'Ketika larutan asam dicampur dengan kertas lakmus biru, warna kertas lakmus akan berubah menjadi...', 'Merah', 'Hijau', 'Kuning', 'Tetap biru', 'A', 'science_in_action'),
(104, 'Peristiwa sifat kelembaman benda (kemampuan mempertahankan keadaan diam/gerak) dijelaskan dalam...', 'Hukum I Newton', 'Hukum II Newton', 'Hukum III Newton', 'Hukum Pascal', 'A', 'science_in_action'),
(105, 'Perubahan wujud zat dari padat langsung menjadi gas tanpa mencair dinamakan...', 'Menguap', 'Menyublim', 'Mengembun', 'Membeku', 'B', 'science_in_action'),
(106, 'Alat laboratorium berbentuk tabung kaca berskala yang digunakan untuk mengukur volume zat cair adalah...', 'Tabung reaksi', 'Gelas ukur', 'Erlenmeyer', 'Pipet tetes', 'B', 'science_in_action'),
(107, 'Sifat bayangan yang dibentuk oleh cermin datar adalah...', 'Maya, tegak, sama besar', 'Nyata, terbalik, diperbesar', 'Maya, terbalik, diperkecil', 'Nyata, tegak, diperkecil', 'A', 'science_in_action'),
(108, 'Sendok logam yang dimasukkan ke dalam cangkir teh panas ikut terasa panas. Peristiwa perpindahan panas ini terjadi secar', '..A. Konveksi', 'Konduksi', 'Radiasi', 'Evaporasi', 'B', 'science_in_action'),
(109, 'Jenis zat terlarut dan pelarut pada campuran air gula, yang bertindak sebagai pelarut adalah...', 'Gula', 'Air', 'Campuran air dan gula', 'Wadah gelas', 'B', 'science_in_action'),
(110, 'Organel sel tumbuhan yang mengandung klorofil untuk fotosintesis adalah...', 'Mitokondria', 'Kloroplas', 'Ribosom', 'Inti sel', 'B', 'science_in_action'),
(111, 'Perpindahan molekul air melalui membran semipermeabel dari larutan encer ke pekat disebut...', 'Difusi', 'Osmosis', 'Transpirasi', 'Kapilaritas', 'B', 'science_in_action'),
(112, 'Hukum Archimedes menyatakan bahwa benda yang dicelupkan ke dalam zat cair akan mengalami gaya ke atas sebesar...', 'Berat benda di udara', 'Berat zat cair yang dipindahkan oleh benda tersebut', 'Volume benda seluruhnya', 'Massa jenis benda', 'B', 'science_in_action'),
(113, 'Nilai pH untuk larutan yang bersifat netral (seperti air murni) adalah...', '0', '7', '14', '1', 'B', 'science_in_action'),
(114, 'Metode pemisahan campuran pasir dan air secara sederhana dengan cara menyaring menggunakan kertas saring dinamakan...', 'Distilasi', 'Filtrasi', 'Kristalisasi', 'Kromatografi', 'B', 'science_in_action'),
(115, 'Energi kinetik dimiliki oleh benda yang sedang...', 'Diam di ketinggian', 'Bergerak memiliki kecepatan', 'Ditekan', 'Dipanaskan', 'B', 'science_in_action'),
(116, 'Satuan Internasional (SI) untuk mengukur suhu adalah...', 'Celsius', 'Kelvin', 'Fahrenheit', 'Reamur', 'B', 'science_in_action'),
(117, 'Bagian mata yang berfungsi mengatur banyaknya cahaya yang masuk ke dalam mata adalah...', 'Kornea', 'Pupil / Iris', 'Lensa', 'Retina', 'B', 'science_in_action'),
(118, 'Gerakan tumbuhan menunduk/menutupnya daun putri malu saat disentuh disebut gerak...', 'Fototropisme', 'Seismonasti / Tigmonasti', 'Hidrotropisme', 'Geotropisme', 'B', 'science_in_action'),
(119, 'Kelompok hewan yang menyusui anaknya tergolong dalam kelas...', 'Reptil', 'Mamalia', 'Aves', 'Ampibi', 'B', 'science_in_action'),
(120, 'Bunyi dapat merambat paling cepat melalui medium...', 'Udara kosong / hampa', 'Benda padat (seperti besi)', 'Air jernih', 'Gas oksigen', 'B', 'science_in_action'),
(121, 'Pesawat sederhana jenis tuas/pengungkit golongan pertama memiliki posisi titik tumpu berada di...', 'Antara beban dan kuasa', 'Di ujung paling kanan', 'Di atas beban', 'Bebas di mana saja', 'A', 'science_in_action'),
(122, 'Gas yang dibutuhkan oleh tumbuhan dalam proses fotosintesis adalah...', 'Oksigen', 'Karbon dioksida ( CO₂ )', 'Nitrogen', 'Helium', 'B', 'science_in_action'),
(123, 'Pembuluh darah yang mengalirkan darah kembali menuju ke jantung adalah pembuluh...', 'Arteri (nadi)', 'Vena (balik)', 'Kapiler', 'Aorta', 'B', 'science_in_action'),
(124, 'Reaksi antara asam dan basa yang menghasilkan garam dan air dinamakan reaksi...', 'Oksidasi', 'Netralisasi', 'Pembakaran', 'Fermentasi', 'B', 'science_in_action'),
(125, 'Cermin yang digunakan pada tikungan jalan untuk melihat kendaraan dari arah berlawanan adalah cermin...', 'Datar', 'Cembung', 'Cekung', 'Cekung-cembung', 'B', 'science_in_action'),
(126, 'Enzim amilase (ptialin) di dalam mulut berfungsi mengubah...', 'Protein menjadi asam amino', 'Amilum (karbohidrat) menjadi gula sederhana', 'Lemak menjadi asam lemak', 'Vitamin menjadi mineral', 'B', 'science_in_action'),
(127, 'Simbol bahaya api pada botol zat kimia laboratorium menandakan bahan tersebut mudah...', 'Meledak', 'Terbakar', 'Beracun', 'Menguap', 'B', 'science_in_action'),
(128, 'Perkembangbiakan vegetatif buatan dengan cara mengupas kulit batang lalu dibungkus tanah humus dinamakan...', 'Stek', 'Mencangkok', 'Merunduk', 'Mengenten', 'B', 'science_in_action'),
(129, 'Pasangan zat yang tergolong unsur kimia adalah...', 'Air dan Garam', 'Oksigen ( O₂ ) dan Besi ( Fe )', 'Udara dan Cuka', 'Gula dan Sirup', 'B', 'science_in_action'),
(130, 'Satuan Internasional (SI) untuk mengukur Gaya adalah...', 'Joule', 'Newton', 'Watt', 'Pascal', 'B', 'science_in_action'),
(131, 'Benda tegar akan berada dalam posisi seimbang jika jumlah gaya yang bekerja padanya bernilai...', 'Maksimal', 'Nol', 'Tak hingga', 'Negatif', 'B', 'science_in_action'),
(132, 'Warna merah pada darah manusia disebabkan oleh adanya protein pengikat oksigen yang dinamakan...', 'Leukosit', 'Hemoglobin', 'Trombosit', 'Plasma', 'B', 'science_in_action'),
(133, 'Pemisahan campuran zat cair berdasarkan perbedaan titik didih dinamakan...', 'Filtrasi', 'Distilasi (Penyulingan)', 'Sublimasi', 'Evaporasi', 'B', 'science_in_action'),
(134, 'Hukum Ohm merumuskan hubungan antara tegangan ( V ), arus ( I ), dan hambatan ( R ) yaitu...', 'V = I  x R', 'V = I / R', 'I = V  x R', 'R = V  x I', 'A', 'science_in_action'),
(135, 'Peristiwa terpisahnya cahaya putih menjadi warna pelangi saat melewati prisma kaca disebut...', 'Pemantulan', 'Dispersi cahaya', 'Pembiasan', 'Penyerapan', 'B', 'science_in_action'),
(136, 'Lensa yang digunakan pada kacamata untuk penderita penderita penderita rabun jauh (Miopi) adalah lens', '..A. Cembung (Positif)', 'Cekung (Negatif)', 'Ganda', 'Datar', 'B', 'science_in_action'),
(137, 'Tekanan udara diukur menggunakan alat yang dinamakan...', 'Termometer', 'Barometer', 'Higrometer', 'Anemometer', 'B', 'science_in_action'),
(138, 'Bakteri Lactobacillus bulgaricus bermanfaat bagi manusia dalam pembuatan...', 'Tempe', 'Yogurt', 'Roti', 'Kecap', 'B', 'science_in_action'),
(139, 'Perubahan energi yang terjadi pada setrika listrik yang sedang digunakan adalah...', 'Energi kimia menjadi panas', 'Energi listrik menjadi energi panas', 'Energi gerak menjadi listrik', 'Energi cahaya menjadi panas', 'B', 'science_in_action'),
(140, 'Magnet yang dibuat dengan cara melilitkan kawat berarus listrik pada paku besi dinamakan...', 'Magnet permanen', 'Elektromagnet', 'Induksi', 'Gosokan', 'B', 'science_in_action'),
(141, 'Proses pembentukan sel sperma pada organ reproduksi laki-laki terjadi di...', 'Ovarium', 'Testis', 'Ginjal', 'Usus', 'B', 'science_in_action'),
(142, 'Organ utama sistem pernapasan manusia tempat terjadinya pertukaran gas oksigen dan CO2 adalah...', 'Lambung', 'Alveolus (di dalam paru-paru)', 'Tenggorokan', 'Jantung', 'B', 'science_in_action'),
(143, 'Sifat bayangan yang dibentuk oleh mikroskop pada pengamatan akhir adalah...', 'Maya, terbalik, diperbesar', 'Nyata, tegak, diperkecil', 'Maya, tegak, sama besar', 'Nyata, terbalik, diperkecil', 'A', 'science_in_action'),
(144, 'Zat tunggal yang tidak dapat diuraikan lagi menjadi zat lain yang lebih sederhana dinamakan...', 'Campuran', 'Unsur', 'Senyawa', 'Larutan', 'B', 'science_in_action'),
(145, 'Gaya gesek yang merugikan dalam kehidupan sehari-hari contohnya adalah...', 'Gesekan rem sepeda dengan pelek roda', 'Gesekan antara ban mobil dan jalan raya', 'Gesekan komponen mesin mobil yang menyebabkan aus', 'Gesekan sepatu dengan lantai agar tidak tergelincir', 'C', 'science_in_action'),
(146, 'Perpindahan panas secara radiasi contohnya adalah...', 'Air mendidih saat dimasak', 'Hangatnya sinar matahari yang sampai ke bumi', 'Cangkir terasa hangat saat diisi air panas', 'Terjadinya angin darat dan angin laut', 'B', 'science_in_action'),
(147, 'Usaha ( W ) dalam fisika didefinisikan sebagai hasil kali antara gaya ( F ) dengan...', 'Massa ( m )', 'Perpindahan ( s )', 'Waktu ( t )', 'Kecepatan ( v )', 'B', 'science_in_action'),
(148, 'Satuan hambatan listrik dalam SI adalah...', 'Volt', 'Ampere', 'Ohm ( Ω )', 'Watt', 'C', 'science_in_action'),
(149, 'Urutan tingkatan organisasi kehidupan dari yang terkecil sampai terbesar yang benar adalah...', 'Sel → Jaringan → Organ → Sistem Organ → Organisme', 'Organ → Sel → Jaringan → Organisme', 'Jaringan → Sel → Organ → Sistem Organ', 'Organisme → Sel → Jaringan → Organ', 'A', 'science_in_action'),
(150, 'Pernyataan dugaan awal yang harus diuji kebenarannya melalui eksperimen dinamakan...', 'Kesimpulan', 'Hipotesis', 'Teori', 'Data', 'B', 'science_in_action'),
(151, 'Hasil dari (-15) + 8 x (-3) adalah...', '21', '-39', '-69', '39', 'B', 'mathematic'),
(152, 'Jika 3x + 7 = 22, maka nilai x adalah...', '3', '5', '7', '15', 'B', 'mathematic'),
(153, 'Bentuk sederhana dari  5a - 3b + 2a + 8b  adalah...', '7a + 5b', '3a + 11b', '10ab', '7a - 5b', 'A', 'mathematic'),
(154, 'Sebuah baju seharga Rp 150.000,00 mendapat diskon 20%. Harga yang harus dibayar adalah...', 'Rp 120.000,00', 'Rp 130.000,00', 'Rp 135.000,00', 'Rp 140.000,00', 'A', 'mathematic'),
(155, 'Nilai dari  adalah...', '19', '21', '23', '25', 'B', 'mathematic'),
(156, 'Sebuah persegi memiliki panjang sisi  12 cm. Luas persegi tersebut adalah...', '48 cm²', '144 cm²', '120 cm²', '240 cm²', 'B', 'mathematic'),
(157, 'FPB dari  24  dan  36  adalah...', '6', '12', '18', '72', 'B', 'mathematic'),
(158, 'KPK dari  6  dan  8  adalah...', '12', '24', '48', '16', 'B', 'mathematic'),
(159, 'Panjang sisi miring segitiga siku-siku dengan alas  9 cm   dan tinggi  12 cm   adalah...', '13    cm', '15    cm', '17    cm', '20    cm', 'B', 'mathematic'),
(160, 'Nilai rata-rata dari nilai matematika: 6, 7, 8, 8, 9 adalah...', '7,4', '7,6', '7,8', '8,0', 'B', 'mathematic'),
(161, 'Hasil dari ¾ + ½ adalah...', '4/6', '5/4', '1', '3/8', 'B', 'mathematic'),
(162, 'Jika  A = {1, 2, 3, 4}   dan  B = {3, 4, 5, 6}  , maka  A irisan B adalah...', '{1, 2}', '{3, 4}', '{5, 6}', '{1, 2, 3, 4, 5, 6}', 'B', 'mathematic'),
(163, 'Sebuah dadu bermata 6 dilempar sekali. Peluang muncul angka ganjil adalah...', '1/6', '1/3', '1/2', '2/3', 'C', 'mathematic'),
(164, 'Keliling lingkaran yang memiliki jari-jari  7 cm   adalah ( π  = 22/7 )...', '22    cm', '44    cm', '154    cm', '88    cm', 'B', 'mathematic'),
(165, 'Luas lingkaran berjari-jari  7    cm   adalah ( π = 22/7 )...', '44    cm²', '154    cm²', '308    cm²', '616    cm²', 'B', 'mathematic'),
(166, 'Nilai dari  2⁴  adalah...', '8', '12', '16', '32', 'C', 'mathematic'),
(167, 'Hasil penjabaran dari  (x + 4)(x + 2)  adalah...', 'x² + 6x + 8', 'x² + 8x + 6', 'x² + 2x + 8', 'x² + 4x + 2', 'A', 'mathematic'),
(168, 'Sebuah mobil memerlukan 3 liter bensin untuk menempuh  45 km  . Jarak yang ditempuh jika mobil diisi 5 liter bensin adalah...', '60    km', '75    km', '90    km', '100    km', 'B', 'mathematic'),
(169, 'Volume kubus yang memiliki panjang rusuk  5 cm   adalah...', '25  cm³', '100 cm³', '125 cm³', '150 cm³', 'C', 'mathematic'),
(170, 'Jika  f(x) = 2x + 5 , nilai dari  f(3)  adalah...', '8', '11', '13', '16', 'B', 'mathematic'),
(171, 'Penyelesaian dari  2x - 4 > 6  adalah...', 'x > 5', 'x < 5', 'x > 1', 'x < 1', 'A', 'mathematic'),
(172, 'Gradien garis dari persamaan  y = 3x - 2  adalah...', '-2', '2', '3', '-3', 'C', 'mathematic'),
(173, 'Luas segitiga dengan alas  10    cm   dan tinggi  6    cm   adalah...', '60    cm²', '30    cm²', '20    cm²', '15    cm²', 'B', 'mathematic'),
(174, 'Median dari data terurut: 3, 5, 7, 8, 9 adalah...', '5', '7', '8', '6', 'B', 'mathematic'),
(175, 'Modus dari kumpulan data: 5, 6, 6, 7, 8, 6, 9 adalah...', '5', '6', '7', '8', 'B', 'mathematic'),
(176, 'Skala peta  1 : 100.000 . Jika jarak pada peta  5 cm  , jarak sebenarnya adalah...', '5    km', '50    km', '500    m', '50    m', 'A', 'mathematic'),
(177, 'Jumlah sudut-sudut dalam sebuah segitiga adalah...', '90°', '180°', '270°', '360°', 'B', 'mathematic'),
(178, 'Hasil dari  4³  adalah...', '12', '16', '64', '256', 'C', 'mathematic'),
(179, 'Sebuah balok memiliki ukuran panjang  10    cm  , lebar  4    cm  , dan tinggi  5    cm  . Volume balok tersebut adalah...', '200    cm³', '100    cm³', '19    cm³', '400    cm³', 'A', 'mathematic'),
(180, 'Suku ke-5 dari barisan aritmatika 2, 5, 8, 11, ... adalah...', '13', '14', '15', '16', 'B', 'mathematic'),
(181, 'Hasil dari  (-4)²  adalah...', '-16', '-8', '16', '8', 'C', 'mathematic'),
(182, 'Perbandingan umur Ani dan Budi adalah  2 : 3 . Jika jumlah umur mereka 20 tahun, umur Budi adalah...', '8    tahun', '12    tahun', '10    tahun', '15    tahun', 'B', 'mathematic'),
(183, 'Luas jajaran genjang dengan alas  8    cm   dan tinggi  5    cm   adalah...', '20    cm²', '40    cm²', '13    cm²', '80    cm²', 'B', 'mathematic'),
(184, 'Besar sudut siku-siku adalah...', '45ᄋ', '90ᄋ', '180ᄋ', '360ᄋ', 'B', 'mathematic'),
(185, 'Jika  x + 5 = 12 , maka nilai  2x  adalah...', '7', '14', '10', '24', 'B', 'mathematic'),
(186, 'Sebuah koin dilempar satu kali. Peluang muncul sisi Angka adalah...', '1/4', '1/2', '1', '0', 'B', 'mathematic'),
(187, 'Keliling persegi yang luasnya  81cm²  adalah...', '9    cm', '36    cm', '18    cm', '81    cm', 'B', 'mathematic'),
(188, 'Hasil dari  10⁰  adalah...', '0', '1', '10', 'Tidak terdefinisi', 'B', 'mathematic'),
(189, 'Suatu pedagang membeli barang seharga Rp 50.000,00 dan menjualnya kembali Rp 60.000,00. Persentase keuntungannya adalah...', '10%', '15%', '20%', '25%', 'C', 'mathematic'),
(190, 'Sumbu simetri bangun layang-layang ada sebanyak...', '1', '2', '3', '4', 'A', 'mathematic'),
(191, 'Hasil dari  3  x (4 + 6) - 5  adalah...', '20', '25', '30', '15', 'B', 'mathematic'),
(192, 'Panjang diagonal bidang kubus yang memiliki rusuk  6 cm   adalah...', '6√2 cm', '6√3 cm', '12    cm', '36    cm', 'A', 'mathematic'),
(193, 'Titik koordinat  A(3, -5)  terletak pada kuadran...', 'I', 'II', 'III', 'IV', 'D', 'mathematic'),
(194, 'Hasil dari ⅖ x 15/4 adalah...', '3/2', '8/75', '3/4', '1', 'A', 'mathematic'),
(195, 'Bentuk  2³ × 2²  jika disederhanakan menjadi...', '2⁵', '2⁶', '4⁵', '4⁶', 'A', 'mathematic'),
(196, 'Sebuah tabung memiliki jari-jari  7    cm   dan tinggi  10    cm  . Luas alas tabung adalah', '154    cm²', '440    cm²', '70    cm²', '308    cm²', 'A', 'mathematic'),
(197, 'Dua garis yang saling sejajar memiliki nilai gradien yang...', 'Berlawanan', 'Sama', 'Berbeda jauh', 'Bernilai nol', 'B', 'mathematic'),
(198, 'Besar sudut lurus adalah...', '90 derajat', '180 derajat', '270 derajat', '360 derajat', 'B', 'mathematic'),
(199, 'Nilai dari  5!  ( 5  faktorial =  5  x 4  x 3  x 2  x 1 ) adalah...', '120', '60', '20', '100', 'A', 'mathematic'),
(200, 'Banyaknya titik sudut pada bangun ruang kubus adalah...', '6', '8', '12', '16', 'B', 'mathematic');